#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""build_vibe_clips.py — collect product videos from Shopify Files, match to products
by alt/title, and write assets/vibe-clips.js (window.VIBE_CLIPS) for the Vibe Clips rail.
Then upload the asset to the given theme id(s).
"""
from __future__ import annotations
import sys, json, re
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import theme_edit as T
import requests

ROOT = Path(__file__).resolve().parents[1] / "theme_assets"


def norm(s):
    return re.sub(r"[^a-z0-9]+", " ", (s or "").lower()).strip()


def main():
    tok = T.token()
    H = {"X-Shopify-Access-Token": tok, "Content-Type": "application/json"}
    gql = T.BASE + "/graphql.json"

    # 1) all product handles + titles (for matching)
    prods = []
    cursor = None
    for _ in range(40):
        q = '{products(first:250%s){pageInfo{hasNextPage endCursor} nodes{handle title featuredImage{url}}}}' % (
            (',after:"%s"' % cursor) if cursor else "")
        d = requests.post(gql, headers=H, json={"query": q}, timeout=60).json()["data"]["products"]
        prods += d["nodes"]
        if not d["pageInfo"]["hasNextPage"]:
            break
        cursor = d["pageInfo"]["endCursor"]
    by_title = {norm(p["title"]): p for p in prods}
    titles = list(by_title.items())
    print(f"products: {len(prods)}")

    STOP = {"with", "your", "kit", "set", "for", "and", "the", "pro"}
    title_tokens = [(set(t for t in nt.split() if len(t) >= 4 and t not in STOP), p) for nt, p in titles]

    def match_product(alt):
        a = norm(alt)
        if not a:
            return None
        if a in by_title:
            return by_title[a]
        at = set(t for t in a.split() if len(t) >= 4 and t not in STOP)
        if not at:
            return None
        best = None; best_score = 0
        for pt, p in title_tokens:
            sc = len(at & pt)
            if sc > best_score:
                best_score = sc; best = p
        # require a solid overlap to avoid false links
        if best_score >= 2 or (best_score >= 1 and len(at) <= 2):
            return best
        return None

    # 2) all video files
    clips = []
    cursor = None
    for _ in range(20):
        q = '{files(first:50,query:"media_type:VIDEO"%s){pageInfo{hasNextPage endCursor} nodes{... on Video{ alt sources{url format mimeType height} preview{image{url}} }}}}' % (
            (',after:"%s"' % cursor) if cursor else "")
        d = requests.post(gql, headers=H, json={"query": q}, timeout=60).json()["data"]["files"]
        for n in d["nodes"]:
            srcs = n.get("sources") or []
            mp4 = next((s for s in srcs if (s.get("mimeType") == "video/mp4" or s.get("format") == "mp4")), None) or (srcs[0] if srcs else None)
            if not mp4:
                continue
            prod = match_product(n.get("alt"))
            poster = (n.get("preview") or {}).get("image") or {}
            from urllib.parse import quote
            if prod:
                url = "/products/" + prod["handle"]
            elif n.get("alt"):
                url = "/search?q=" + quote(n["alt"])
            else:
                url = "/collections/all"
            clips.append({
                "v": mp4["url"],
                "poster": poster.get("url", ""),
                "url": url,
                "title": (prod["title"] if prod else (n.get("alt") or "Wanelo Clip")),
            })
        if not d["pageInfo"]["hasNextPage"]:
            break
        cursor = d["pageInfo"]["endCursor"]
    # dedup by video url
    seen = set(); uniq = []
    for c in clips:
        if c["v"] in seen:
            continue
        seen.add(c["v"]); uniq.append(c)
    print(f"video clips: {len(uniq)} (matched to products: {sum(1 for c in uniq if c['url'].startswith('/products/'))})")

    asset = "/* auto-generated by build_vibe_clips.py — product videos for the Vibe Clips rail */\nwindow.VIBE_CLIPS = " + json.dumps(uniq, ensure_ascii=False) + ";\n"
    out = ROOT / "assets" / "vibe-clips.js"
    out.write_text(asset, encoding="utf-8")
    print("wrote", out, len(asset), "bytes")

    for tid in sys.argv[1:]:
        sc, _ = T.upload(tok, tid, "assets/vibe-clips.js", asset)
        print("upload to theme", tid, "->", sc)
    return 0


if __name__ == "__main__":
    sys.exit(main())
